### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by Ericvf** [schwoi/UnifiClient#10]
I've noticed that it's hard to extend the `Client` class. Internally you are leveraging partial classes. But those consuming this package via `Nuget` have to rely on polymorphism. It would be great to have access to the `ExecuteJsonCommandAsync` method for example.

That way I can write a derived client class with additional API calls, e.g. GetEvents (which is what I needed), without having to clone and compile the library.

```csharp
public class BetterUnifiControllerClientNoOffense : UnifiApi.Client
{
    public async Task<BaseResponse<Event>> GetEventsAsync(int start = 0, int limit = 1000, int within = 4320)
    {
        var path = $"/api/s/{Site}/stat/event";

        var oJsonObject = new JObject();
        oJsonObject.Add("_start", start);
        oJsonObject.Add("_limit", limit);
        oJsonObject.Add("within", within);

        var response = await ExecuteJsonCommandAsync(path, oJsonObject); // <-- currently not possible
        return JsonConvert.DeserializeObject<BaseResponse<Event>>(response.Result);
    }
}
```

**Comment by schwoi** [comment]
Hey @Ericvf sounds like a good idea. I will have a look at it when I can. 
Alternatively if you need it quicker, put through a PR.

**Comment by Ericvf** [comment]
Allright thanks. Here is a PR: #12

**Comment by Ericvf** [comment]
Nice
