### ISSUE TITLE
Device.X and Device.Y are long? but should be decimal?

### ISSUE THREAD

**Issue by Imar** [schwoi/UnifiClient#5]
In the Device class (https://github.com/schwoi/UnifiClient/blob/master/UnifiClient/UnifiApi/Models/Device.cs) X and Y are marked as long:

public long? X { get; set; }
public long? Y { get; set; }

However, that makes them a rounded number and causes them to lose a lot of precision which makes them useless as coordinates. Changing them to decimal? fixes the issue:

public decimal? X { get; set; }
public decimal? Y { get; set; }

Great library, BTW. Exploring it now and integration to an app I am building.

**Comment by schwoi** [comment]
Good pick up @Imar, thanks.
I will fix this and push it out shortly.

**Comment by schwoi** [comment]
Fixed in V1.0.0.10
