### ISSUE TITLE
Rename Client or Add Note

### ISSUE THREAD

**Issue by elciomsantana** [schwoi/UnifiClient#9]
I'm not able to add a note to the customer and I also needed to change the friendly name.

Is this possible?

thank you!

![image](https://user-images.githubusercontent.com/76231121/106787347-5e351d00-662e-11eb-8199-5c87dd1aae91.png)

**Comment by elciomsantana** [comment]
![2021-02-10$15 52 40 765](https://user-images.githubusercontent.com/76231121/107557808-d49ac780-6bb8-11eb-8aeb-d58e60d504ff.png)


Hi?

**Comment by schwoi** [comment]
@elciomsantana sorry this has taken so long for me to look at.
The first one renaming the device you need to use the Device ID and not the MAC.
and the Client Note has changed from MAC to ID also. I am pushing an update to fix the parameter names for this now but you would need to update you side.
